### ISSUE TITLE
getpeername() fails during Client constructor

### ISSUE THREAD

**Issue by tilsche** [jrosdahl/miniircd#15]
I use a heavily modified version of miniircd. I recently had a crash with that trace:

      (self.host, self.port) = client_socket.getpeername()
    File "/usr/lib/python2.7/socket.py", line 224, in meth
      return getattr(self._sock,name)(*args)
    socket.error: [Errno 107] Transport endpoint is not connected

apparently if a client disconnects really quickly after connecting (or maybe it's some other odd timing behavior), the Client constructor throws from getpeername(). I fixed it in my fork with a generous try/catch can't really say I tested it though.

Maybe this helps you also to fix it or maybe you have a better fix.

**Comment by jrosdahl** [comment]
Thanks. I've added a try/catch along those lines.

> fixed it in my fork with a generous try/catch can't really say I tested it though.

Well, I would expect that

```
del self.clients[conn]
```

will raise `KeyError` since no entry is added to `self.clients` if the `Client` constructor raises an exception. ;-)
