### ISSUE TITLE
How to deploy miiniircd on Openshift?

### ISSUE THREAD

**Issue by Schezuk** [jrosdahl/miniircd#17]
I have a python application slot on Openshift on which I would like to deploy miniircd.
I would appreciated it if you can show me how, since I am only familiar to PHP deployment, i.e., simply uploading PHP files.

**Comment by prologic** [comment]
Have you read thorugh this documentation: https://developers.openshift.com/en/python-overview.html ?

**Comment by prologic** [comment]
Also not to be rude to the original author; but you perhaps *may* want to look at an alternative I wrote a few months ago which has a few more features than miniircd.

[charla](https://github.com/prologic/charla) -- This also has fully support for deplotying via Docker (*which I think Openshift uses itself*).

**Comment by Schezuk** [comment]
@prologic Yes, and the document confused me. I tried for a whole night to figure out how WSGI works on rhcloud and how to setup miniircd, but failed.

Charla seems great, though I have no idea if it support pass phrase or not. 

However, installation on Openshift still comes to error. Lots of warnings and errors was thrown out, the last line of which said "ImportError: No module named dateutil.tz".

**Comment by prologic** [comment]
I don't think miniircd will support passphrase either :) What is this feature anyway? Also neither miniircd nor charla are WSGI apps; WSGI is a web thing :)

**Comment by Schezuk** [comment]
Err...sorry, I mean password.
I didn't know IRC is not WSGI-compatible. So is it possible to run an IRS on PaaS like Openshift(no matter what the language it)?
Thank you anyway.

**Comment by prologic** [comment]
I *think* it's definitely still possible to run miniircd on OpenShift; it's just if you're following WSGI general deployment guidelines you're going to be led astray :) -- Also password protected server is a feature I'll be implementing in charla very soon

**Comment by Schezuk** [comment]
Yeah, possible, maybe. Openshift has strict limitation on port usage and so forth.
I will try again next day. Thank you for your kindness.
Happy Christmas Eve,

**Comment by prologic** [comment]
No problems :) Btw; have you considered just running something up on [DigitalOcean](https://www.digitalocean.com/)? Example:

```#!bash
docker-machine create -d digitealocean --digitalocean-access-token <digiteal_ocean_access_token> test
eval $(docker-machine env test)
docker run -d 7000:7000 prologic/charla
irssi -c $(docker-machine ip test) -p 7000
```

Have a nice holiday!

**Comment by jrosdahl** [comment]
> I don't think miniircd will support passphrase either :)

Well, requiring a password is one of the few features that miniircd actually *does* implement.

> I have a python application slot on Openshift on which I would like to deploy miniircd. I would appreciated it if you can show me how [...]

Sorry, support requests like these are out of scope for the issue tracker, so I'll close it. I don't know anything about Openshift, but I hope that you'll get it working somehow! :-)

**Comment by prologic** [comment]
Sadly neither do i :) I tend to run up everything in Docker containers
these days :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by Schezuk** [comment]
Well, requiring a password is one of the few features that miniircd actually does implement.
Yes, I did notice that. From a minimalist ircd it's inapposite to expect more.

    Sorry, support requests like these are out of scope for the issue tracker, so I'll close it. I don't know anything about Openshift, but I hope that you'll get it working somehow! :-)
Emm, I move on to XMPP over BOSH. There are some PHP libraries for Jabber which I hope I can figure out how they works. Anyway thank you very much.

    Sadly neither do i :) I tend to run up everything in Docker containers these days :)
Docker seams a good idea. Would you recommend some Docker hoster which requires no credit-card binding, please?

**Comment by prologic** [comment]
On Tue, Dec 29, 2015 at 5:00 PM, Schezuk <notifications@github.com> wrote:

> Docker seams a good idea. Would you recommend some Docker hoster which
> requires no credit-card binding, please?


You mean; Docker-based hosting that is FREE?
I'm afraid almost no-one offers FREE Hosting :)

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by Schezuk** [comment]
No, I mean to pay via Paypal or by prepaid card or with Bitcoin or anything BUT credit card.

**Comment by prologic** [comment]
Oh I see; Let's move this off-site (as it's kind of off-topic). Feel free
to email me as I might have some ideas around this :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
