### ISSUE TITLE
Python 2.5 support

### ISSUE THREAD

**Issue by Symbian9** [jrosdahl/miniircd#20]
Is it possible run it on Python 2.5 or older?
Also, can it work without SSL?

**Comment by jrosdahl** [comment]
> Is it possible run it on Python 2.5 or older?

No, see https://github.com/jrosdahl/miniircd#requirements. If you really want to, it should be easy to tweak it to work with Python 2.5 by using the `expect X, Y` syntax instead of `expect X as Y` for catching exceptions.

> Also, can it work without SSL?

Yes.
