### ISSUE TITLE
how to use for dummies

### ISSUE THREAD

**Issue by LoganDark** [jrosdahl/miniircd#21]
Just a very basic tutorial with instructions to get it working at its most basic level.

**Comment by prologic** [comment]
It's very simple:

# Quick Start

1. Clone this repository:

```#!bash
git clone https://github.com/jrosdahl/miniircd
```

2. Run `miniircd`:

```#!bash
cd miniircd
./miniircd
```

3. Connect to it!

`/server localhost` (*or your external IP Address*).

You may need to use `--listen=0.0.0.0` to bind to all interfaces so external clients can connect.

----

You may also be interested in an IRC Daemon that has a few more features and active development [charla](https://github.com/prologic/charla) that took some inspiration from miniircd.

Enjoy! :)
