### ISSUE TITLE
--pid-file and -d don't work together

### ISSUE THREAD

**Issue by atoms118** [jrosdahl/miniircd#40]
Using `--pid-file` alone works fine, as does `-d`, but when using both at the same time the program exits immediately. Passing `--debug` causes it to output the PID to console but no other output appears.

**Comment by atoms118** [comment]
Quick update, running with the v1.3 release instead of the latest commit results in the error message `Could not create PID file 'miniircd.pid'` and doesn't print the PID to console when `--debug` is passed, but otherwise behaves the same.

**Comment by atoms118** [comment]
Sorry for the flood of notifications, but it seems like it *does* work when passing `--pid-file` as an absolute path (as opposed to `miniircd.pid` or `./miniircd.pid`). Strangely enough it does work with all paths when not running as a daemon.

**Comment by jrosdahl** [comment]
Thanks for the bug report! It seems like `--pid-file` has never worked with a relative path in combination with `-d` so it's not a regression.

The reason why it doesn't work is that miniircd changes the current directory to "/" as part of the daemonization and the writing of the PID file is done _after_ that.
