### ISSUE TITLE
Writing multibyte characters

### ISSUE THREAD

**Issue by Zulan** [jrosdahl/miniircd#41]
I believe there is an issue with this part of the send code (considering Python 3 and unicode strings):

https://github.com/jrosdahl/miniircd/blob/3070b4c094a23809461d3d5d501c44423d84042e/miniircd#L610

`self.__writebuffer` is a `str`, but `sent` counts the number of bytes. So if there are multibyte characters in buffer, this will not cause the expected behavior.

I think the cleanest solution is to make the `__writebuffer` a `bytearray` and do the encoding earlier.

**Comment by jrosdahl** [comment]
Thanks! I think it's time to drop Python 2 support.

**Comment by Zulan** [comment]
Thanks for addressing this so swiftly and thoroughly!

The type checking actually helps me a lot. I maintain a fork that supports a crude encryption protocol by a game client and I've been pushing this to Python 3. Your work is much appreciated.
