### ISSUE TITLE
SSL error for connection from ip: [SSL] PEM lib (_ssl.c:3524)

### ISSUE THREAD

**Issue by KoxSosen** [jrosdahl/miniircd#44]
Hello!

I just finished setting up miniircd. I generated an ssl cert using cerbot:
```certbot certonly --standalone --preferred-challenges http-01 -d  my.domain.example```
I gave the user that I'm using the server with access to the keys.
```
root@root:~# chown irc:irc /etc/letsencrypt/live/my.domain.example/etc/letsencrypt/archive/my.domain.example/ -R
root@root:~# chmod g+r,o-rwx /etc/letsencrypt/live/imy.domain.example/etc/letsencrypt/archive/my.domain.example/ -R
```

I started the server with the following parameters:
```
./miniircd --debug --channel-log-dir /home/log/ --listen iphere --ports 6697 --motd test.txt -s /etc/letsencrypt/live/my.domain.example/fullchain.pem --verbose
```

But, when connecting with ssl, I get an error:

```SSL error for connection from 87.9.424227:55825: [SSL] PEM lib (_ssl.c:3524)```

**Comment by jrosdahl** [comment]
The file specified by `-s` should contain both the private key and the certificate. You can construct it with something like `cat /etc/letsencrypt/live/my.domain.example/fullchain.pem /etc/letsencrypt/live/my.domain.example/privkey.pem >combined.pem` and then use `-s combined.pem`.

I've never used the SSL mode myself so it hasn't occurred to me before, but it would certainly make sense to support specifying the key and certificate files separately.

**Comment by jrosdahl** [comment]
That was easily done. :slightly_smiling_face:

**Comment by KoxSosen** [comment]
Thank you!
