### ISSUE TITLE
[Suggestions] for miniircd

### ISSUE THREAD

**Issue by KoxSosen** [jrosdahl/miniircd#45]
Hello!

Thank you for adding the options for the ssl cert last time. Sadly, it keept giving me an issue, but the command you gave me in a comment fixed all issues I had.

I've got two suggestions that I think would he amazing for miniircd, and "won't break it's simplicity".

**1** - Password for channels, not the enteire irc server.

- We have a password that we can set for the server, but we can't set passwords for channels. This would be amazing, as it would allow me to run my private and public irc channels in the same server. My idea is an option like `-cp #example car123` . 
( `--channel-password #example password` )

**2** - Irc channel history displaying when connecting to a channel.

At the moment, when you connect to a channel, you can't see it's history, and it's hard to join into the chat if you have a crappy internet, and you have to rejoin every minute. My idea is, when the log option is specifyed, and enabled, read the history from the logs, and display it to the user when connecting. 
`-sh #example`.
( `--show-history #example`) ( )

Thank you for reading!

**Comment by jrosdahl** [comment]
Thanks for the suggestions.

Regading suggestion 1: Since channels are dynamic in nature I don't think it's a good to specify channel passwords as startup options – to be able to set or change a channel password you would then need to restart the server which will throws out all users.

Regarding suggestion 2: This doesn't sound like something for an IRC daemon to do. I would suggest using a bot for similar effect instead.

**Comment by KoxSosen** [comment]
Hello!

About suggestion 1, yes, I agree, it might not be the best solution. Maybe a command for setting a channels password?

**Comment by KoxSosen** [comment]
Regarding suggestion two, may can I ask, do you have any recommendations?

**Comment by jrosdahl** [comment]
> About suggestion 1, yes, I agree, it might not be the best solution. Maybe a command for setting a channels password?

Right, that would be implementing support for the `/MODE #channel +k password` command.

> Regarding suggestion two, may can I ask, do you have any recommendations?

Not really. I haven't really been using IRC for about 15 years so I don't know what's available these days. :slightly_smiling_face:

**Comment by KoxSosen** [comment]
> available

Allright, thank you! I belive I found my solution for channel history showing ( https://wiki.znc.in/ZNC ).
