### ISSUE TITLE
Server crash if state file(s) contain strings

### ISSUE THREAD

**Issue by mmaney** [jrosdahl/miniircd#48]
Okay, maybe I missed a mention of this, but neither have I been doing frequent upgrades, as I just replaced the old 1.? version that's been running for ages under Py2.  Anyway, the old [channel] state file had a plain old string assigned to topic, and while the file is read with the 'b' flag, that has no effect on how the literal is interpreted when it gets exec'd.

Manually editing that file to make it a bytes literal fixed this crash, of course.  But that's a nice loophole where a non-bytes string can get injected into the server, leading to crash when it's eventually used as an argument to a bytes format string.  Hmmm, I may have a couple other files to fix, now that I think about it...

I haven't got any clear vision of where this might go.  For myself, I'd be happy if this (and other potentially user-supplied texts such as motd, maybe some CL arguments) were at least prepared to accept a unicode text, but I suppose that there are others who even at this late date would be made unhappy by just making that the default.  :-/

**Comment by jrosdahl** [comment]
> Okay, maybe I missed a mention of this

It wasn't mentioned anywhere, but yes, users apparently have to fix their state files when upgrading to 2.x.

>  But that's a nice loophole where a non-bytes string can get injected into the server, leading to crash when it's eventually used as an argument to a bytes format string.

Not sure understand this part. Could you expand on what you mean?

Do you just mean that if the state file is incorrect then miniircd can crash? If so, that's true and not something I think is worth thinking too much about...

> were at least prepared to accept a unicode text

Note that there is no such thing as a Unicode textfile; you'll have to associate the content with an encoding, either implicitly or explicitly.
