### ISSUE TITLE
logfile is in byte format instead of string

### ISSUE THREAD

**Issue by Hurgotron** [jrosdahl/miniircd#52]
I think this looks cumbersome

```
[2022-10-12 21:03:32 UTC] * b'Brin' b'joined'
[2022-10-12 21:03:41 UTC] <b'Brin'> b'sl\xc3\xb6del bad\xc3\xb6del'
[2022-10-12 21:04:05 UTC] * b'Brin' b'quit (Leaving)'
```
and especially the German umlauts can't really be read easily. (Maybe there's a reason for this choice of logfile format, but I can't come up with one.)

**Comment by jrosdahl** [comment]
It's not a choice of log file format; it's just a bug in the porting work from Python 2 to Python 3.

**Comment by Hurgotron** [comment]
Thanks for the quick fix. Please consider to convert the topic logging to string, too.
```
* Brin set topic to b'Test test TEST T\xc3\x84ST'
 ```

**Comment by jrosdahl** [comment]
> Please consider to convert the topic logging to string, too.

Done.
